[build]
default-target = "aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./etc/armv7-unknown-linux-gnueabihf/Dockerfile"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./etc/aarch64-unknown-linux-gnu/Dockerfile"
