use crate::chunk::*;
use serde_json::Value;
use lalrpop_util::ParseError;

grammar;

match {
    r"#[^\n\r]*[\n\r]*" => {},
    r"\s*" => {},
} else {
    _
}

pub Chunk: Chunk = {
    Expr => Chunk(vec![<>]),
    <mut c:Chunk> <e:Expr> => {
        c.0.push(e);
        c
    },
};

Expr: Expr =  {
    ";" => Expr::Nop,
    "return" <v:RetValue> => Expr::Ret(v),
    "$" <p:ValPath> "=" <v:OptionValue> => Expr::Set(p, v),
    "print" "$" <ValPath> => Expr::Print(<>),
}

ValPath: Vec<Value> = {
    <mut p:ValPath> "." <i:ValPathItem> => {
        p.push(i);
        p
    },
    ValPathItem => vec![<>],
}

ValPathItem: Value = {
    r"-?[0-9]+" =>? <>.parse::<i64>().map(Value::from).map_err(|_| ParseError::User {
      error: "parse i64"
    }),
    r"[a-zA-Z][a-zA-Z0-9_]*" => Value::from(<>)
}

RetValue: Value = {
    r"-?[0-9]+" =>? <>.parse::<i64>().map(Value::from).map_err(|_| ParseError::User {
      error: "parse i64"
    })
}

OptionValue: Value = {
    r"-?[0-9]+" =>? <>.parse::<i64>().map(Value::from).map_err(|_| ParseError::User {
      error: "parse i64"
    })
}



// vim: sw=4 si
