use crate::chunk::*;
use serde_json::Value;
use lalrpop_util::ParseError;

grammar;

pub Chunk: Chunk = {
    Expr => Chunk(vec![<>]),
    <mut c:Chunk> <e:Expr> => {
        c.0.push(e);
        c
    },
};

Expr: Expr =  {
    ";" => Expr::Nop,
    "return" <v:Value> ";" => Expr::Ret(v),
}

Value: Value = {
    r"-?[0-9]+" =>? <>.parse::<i32>().map(Value::from).map_err(|_| ParseError::User {
      error: "parse i32"
    })
}
